# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: somethingxdev/zavet39

media_folder: /assets

media_libraries:
  default:
    config:
      max_file_size: 1024000 # default: Infinity
      slugify_filename: true # default: false

singletons:
  - name: gallery
    label: Галерея
    file: /src/data/gallery.json
    fields:
      - name: items
        label: Фотографии
        widget: list
        summary: '{{fields.alt}}'
        fields:
          - { label: Изображение, name: image, widget: image, media_folder: /src/assets/gallery }
          - { label: Alt, name: alt, widget: string }
  - name: contacts
    label: Контакты
    file: /src/data/contacts.json
    fields:
      - { label: Заголовок страницы, name: pageTitle, widget: string }
      - { label: Заголовок адреса, name: addressLabel, widget: string }
      - { label: Адрес, name: address, widget: text, hint: 'Можно указывать адрес в несколько строк' }
      - { label: Заголовок телефонов, name: phoneLabel, widget: string }
      - { label: Телефон (для отображения), name: phoneDisplay, widget: string }
      - { label: Телефон (для ссылки, без символов), name: phoneHref, widget: string, hint: 'Пример: +79106367313' }
      - { label: Заголовок email, name: emailLabel, widget: string }
      - { label: Email, name: email, widget: string }

collections:
  - name: monuments
    label: Памятники
    label_singular: Monument
    editor:
      preview: false
    folder: /src/data/monuments
    create: true
    fields:
      - { label: Название, name: title, widget: string }
      - { label: Изображение, name: image, widget: image, media_folder: /src/assets/services/monuments }
      - { label: Материалы, name: materials, widget: text }
      - name: dimensionsAndPrice
        label: Размеры и стоимость
        widget: list
        fields:
          - { label: Размеры, name: dimensions, widget: string }
          - { label: Стоимость, name: price, widget: string }
      - name: type
        label: Подкатегория
        widget: select
        required: false
        options:
          - { label: Вертикальный, value: 'vertical' }
          - { label: Горизонтальный, value: 'horizontal' }
          - { label: Гранитный крест, value: 'granite-cross' }
          - { label: Комбинированный, value: 'combined' }
          - { label: Резной, value: 'carved' }
          - { label: Мраморная крошка, value: 'marble-chips' }
  - name: improvement
    label: Благоустройство
    label_singular: Improvement
    editor:
      preview: false
    folder: /src/data/improvement
    create: true
    fields:
      - { label: Название, name: title, widget: string }
      - { label: Изображение, name: image, widget: image, media_folder: /src/assets/services/improvement }
      - { label: Материалы, name: materials, widget: text }
      - { label: Размеры, name: dimensions, widget: string }
      - { label: Стоимость, name: price, widget: string }
      - name: type
        label: Подкатегория
        widget: select
        required: false
        options:
          - { label: Подиумы, value: 'socles' }
          - { label: Бордюры, value: 'curbs' }
  - name: complexes
    label: Комплексы
    label_singular: Complex
    editor:
      preview: false
    folder: /src/data/complexes
    create: true
    fields:
      - { label: Название, name: title, widget: string }
      - { label: Изображение, name: image, widget: image, media_folder: /src/assets/services/complexes }
      - { label: Материалы, name: materials, widget: text }
      - { label: Размеры, name: dimensions, widget: string }
      - { label: Стоимость, name: price, widget: string }
      - name: type
        label: Подкатегория
        widget: select
        required: false
        options:
          - { label: Вертикальные, value: 'vertical' }
          - { label: Горизонтальные, value: 'horizontal' }
          - { label: Гранитные кресты, value: 'granite-cross' }
          - { label: Комбинированные, value: 'combined' }
          - { label: Резные, value: 'carved' }
          - { label: Мраморная крошка, value: 'marble-chips' }
  - name: fences
    label: Ограды
    label_singular: Fence
    editor:
      preview: false
    folder: /src/data/fences
    create: true
    fields:
      - { label: Название, name: title, widget: string }
      - { label: Изображение, name: image, widget: image, media_folder: /src/assets/services/fences }
      - { label: Материалы, name: materials, widget: text }
      - { label: Размеры, name: dimensions, widget: string }
      - { label: Стоимость, name: price, widget: string }
      - name: type
        label: Подкатегория
        widget: select
        required: false
        options:
          - { label: Металлические, value: 'metal' }
          - { label: Кованые, value: 'forged' }
          - { label: Гранитные, value: 'granite' }
  - name: benches-and-tables
    label: Лавочки и столики
    label_singular: BenchAndTable
    editor:
      preview: false
    folder: /src/data/benches-and-tables
    create: true
    fields:
      - { label: Название, name: title, widget: string }
      - { label: Изображение, name: image, widget: image, media_folder: /src/assets/services/benches-and-tables }
      - { label: Материалы, name: materials, widget: text }
      - { label: Размеры, name: dimensions, widget: string }
      - { label: Стоимость, name: price, widget: string }
      - name: type
        label: Подкатегория
        widget: select
        required: false
        options:
          - { label: Лавочки, value: 'benches' }
          - { label: Столики, value: 'tables' }
          - { label: Комплекты, value: 'sets' }
  - name: crosses
    label: Кресты
    label_singular: Cross
    editor:
      preview: false
    folder: /src/data/crosses
    create: true
    fields:
      - { label: Название, name: title, widget: string }
      - { label: Изображение, name: image, widget: image, media_folder: /src/assets/services/crosses }
      - { label: Материалы, name: materials, widget: text }
      - { label: Размеры, name: dimensions, widget: string }
      - { label: Стоимость, name: price, widget: string }
      - name: type
        label: Подкатегория
        widget: select
        required: false
        options:
          - { label: Гранитный крест, value: 'granite' }
          - { label: Металлический крест, value: 'metal' }
  - name: monument-design
    label: Оформление памятника
    label_singular: MonumentDesign
    editor:
      preview: false
    folder: /src/data/monument-design
    create: true
    fields:
      - { label: Название, name: title, widget: string }
      - { label: Изображение, name: image, widget: image, media_folder: /src/assets/services/monument-design }
      - { label: Описание, name: materials, widget: text }
      - { label: Размеры, name: dimensions, widget: string, required: false }
      - { label: Стоимость, name: price, widget: string }
      - name: type
        label: Подкатегория
        widget: select
        required: false
        options:
          - { label: Гравировка портрета, value: 'portrait-engraving' }
          - { label: Гравировка букв, value: 'letter-engraving' }
          - { label: Шрифты, value: 'fonts' }
          - { label: Буквы из металла, value: 'metal-letters' }
          - { label: Религиозная гравировка, value: 'religious-engraving' }
          - { label: Комплекс гравировки, value: 'engraving-complex' }
  - name: accessories
    label: Аксессуары
    label_singular: Accessory
    editor:
      preview: false
    folder: /src/data/accessories
    create: true
    fields:
      - { label: Название, name: title, widget: string }
      - { label: Изображение, name: image, widget: image, media_folder: /src/assets/services/accessories }
      - { label: Материалы, name: materials, widget: text }
      - { label: Размеры, name: dimensions, widget: string }
      - { label: Стоимость, name: price, widget: string }
      - name: type
        label: Подкатегория
        widget: select
        required: false
        options:
          - { label: Вазы, value: 'vases' }
          - { label: Лампады, value: 'lamps' }
          - { label: Крестики, value: 'small-crosses' }
          - { label: Цветы, value: 'flowers' }
